### ISSUE TITLE
Some improvements & Problems

### ISSUE THREAD

**Issue by avbrowne-web** [jkniest/HTMLCache#4]
Hi.

I've created something pretty similar to this and want to bring up a couple things for you to consider. Apologies if you're already aware of these or working on it, I haven't had time to test any of this it's just from reading over the middleware.

- Using ->path() doesn't include the get request so /about?foo=bar will have the same cache key as /about?foo=else 
- Why not just hash ->getRequestUri(), no need to make a readable cache name is there?
- You probably want to make sure the response status code is 200 before caching.
- Should only cache GET requests
- Don't cache if old() has anything.
- Create a new response object each time to get a new CSRF token in the headers.

**Comment by jkniest** [comment]
Hey, thanks for your suggestions.

> Using ->path() doesn't include the get request so /about?foo=bar will have the same cache key as /about?foo=else

This is intended. Currently I have no plans to add GET parameters. In the README file there is a simple tutorial to add specific GET parameters and for the next version the `page` parameter is planned to implement. I will think about implementing all get parameters.

> Why not just hash ->getRequestUri(), no need to make a readable cache name is there?

That is true. I will look into it. The only reason I chose readable cache names is that there are multiple factors playing a role in the cache key (the language, user id and custom added properties). 

> You probably want to make sure the response status code is 200 before caching.

That is a pretty good suggestion. I honestly haven't thought about it. I will add it in the next release.

> Should only cache GET requests

Is already only caches GET requests. [Code that is responsible](https://github.com/jkniest/HTMLCache/blob/develop/src/Http/Middleware/CacheHtml.php#L111)

> Don't cache if old() has anything.

Also a good idea. So if the errorbag does contains some validation errors for example it should not cache the page. I probably will implement this in the next release. I am not sure if I want to make this configurable..

> Create a new response object each time to get a new CSRF token in the headers.

That is a little bit harder I guess. Since it caches the whole html result the csrf-token meta field will be cached too. I need to think of a way I can solve this. Currently any programmer could also remove the csrf meta field from their html structure and it wouldn't be there so there is no guaranty that this field exists. I will of course think about a solution.

---

And again, thank you for yours suggestions. 

Have a nice day,
Jordan

**Comment by jkniest** [comment]
Hey,

I have just pushed a new release (1.0.2) which solves a few of the issues. See this PR: #6.

> Using ->path() doesn't include the get request so /about?foo=bar will have the same cache key as /about?foo=else

I will implement this in the next bigger release (1.1.*), because it would be a bigger change and could change existing pages.

> Why not just hash ->getRequestUri(), no need to make a readable cache name is there?

I have thought about it and you are right. This would also solve some problems with special characters. It is planned for the next release.

> You probably want to make sure the response status code is 200 before caching.

Done in 1.0.2

> Don't cache if old() has anything.

Done in 1.0.2

---

I will close this issue for now, but I will come back when I start working on some of the other things here :-)

Thank you!

**Comment by jkniest** [comment]
I have just released a new version which contains the GET parameter caching (and also PHP7.2) support. See #10 and #12
